version: '3'

services:
  bridge:
    build: .
    restart: always
    command: sleep infinity
    ports:
      - 15672:15672
   
  devenv:
    image: stono/devenv
    network_mode: 'service:bridge'
    command: /bin/bash 
    build: .
    volumes:
      - ~/.ssh:/home/docker/.ssh:ro
      - ~/.gitconfig:/home/docker/.gitconfig
      - code:/storage

  redis:
    image: redis:3.2.8
    network_mode: 'service:bridge'
    restart: always

  rabbitmq:
    image: rabbitmq:3.6.9-management 
    network_mode: 'service:bridge'
    restart: always
    
volumes:
  code:
